### ISSUE TITLE
Value with backslashes causes LineParse error

### ISSUE THREAD

**Issue by Boscop** [slapresta/rust-dotenv#64] opened 2017-04-21 03:11 UTC
When I have a value with backslashes, like a path, e.g. `FOO_FOLDER="D:\projects\foo"`, I get an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LineParse("\"D:\\projects\\foo\""), State { next_error: None, backtrace: S
ome(stack backtrace:
...
```
It works with double backslashes or single quote, but it should work like above too.

**Comment by slapresta** [comment] 2017-04-21 08:54
As mentioned on #63, using single quotes should do the trick. I believe this issue is a duplicate of #63, so I'm closing it; feel free to reopen it if it's not!

**Closed by slapresta** 2017-04-21 08:54 UTC
